LIB = lib
SRCDIR = src
BINDIR = bin
TESTDIR = test
DOCDIR = doc

CLI = $(LIB)/cli/commons-cli-1.3.1.jar
ASM = $(LIB)/asm/asm-5.0.4.jar:$(LIB)/asm/asm-commons-5.0.4.jar:$(LIB)/asm/asm-tree-5.0.4.jar
JUNIT = $(LIB)/junit/junit-4.12.jar:$(LIB)/junit/hamcrest-core-1.3.jar
TOOLS = $(LIB)/tool

JFLAGGS = -g -d $(BINDIR) -cp $(BINDIR):$(JUNIT)
JAVAC = javac
JVM = java

vpath %.java $(SRCDIR)/:$(TESTDIR)
vpath %.class $(BINDIR)/:$(BINDIR)/test

.SUFFIXES: .java .class

.java.class:
	$(JC) $(JFLAGS) $<

all: BinaryTree.class BinaryTreeNode.class PrintIt.class SearchIt.class SearchItLinear.class

doc:
	javadoc -d $(DOCDIR) -link http:/docs.oracle.com/javase/8/docs/api/$(SRCDIR)/*.java

test_classes: \

test: test_classes
	java -ea -cp $(BINDIR):$(JUNIT)org.junit.runner.JUnitCore TestSuite



clean:
	@rm -f  $(BINDIR)/*.class
	@rm -f $(BINDIR)/*/*.class
	@rm -Rf doc

	
